name: RegressionTests

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
                
    - name: Run regression testing suite
      run: |
        export PYTHONPATH="$PYTHONPATH:$(pwd)/MAPLEAF"
        mapleaf-batch