name: Tests

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install coverage
                
    - name: Test with unittest
      run: |
        export PYTHONPATH="$PYTHONPATH:$(pwd)/MAPLEAF"
        python -m coverage run --source=./MAPLEAF -m unittest discover -v
        
    - name: Upload coverage results
      run: |
        export CODECOV_TOKEN="661ab77b-8643-44a9-8cc5-95954863ff40"
        bash <(curl -s https://codecov.io/bash)
